program Yeganeh_DCash_V_4;
uses
  Windows,
  SysUtils,
  ShellApi,
  TINYLib_TLB,
  Forms,
  ConnectU in 'ConnectU.pas' {FrConnect},
  BaseUnit in 'BaseUnit.pas' {YBaseForm},
  dmu in 'Dmu.pas' {dm: TDataModule},
  BusinessLayer in 'BusinessLayer.pas',
  AddTemplateU in 'AddTemplateU.pas' {FrAddTemplate},
  YInputQuery in 'YInputQuery.pas' {YInputQueryF},
  YeganehDemo in 'YeganehDemo.pas' {Yeganeh},
  AddUserU in 'AddUserU.pas' {FrAddUser},
  ShowmessageU in 'ShowmessageU.pas' {ShowMessageF},
  LoginU in 'LoginU.pas' {FrLogin},
  ChangePassU in 'ChangePassU.pas' {FrChangePass},
  AddContactU in 'AddContactU.pas' {FrAddContact},
  AddPaymentU in 'AddPaymentU.pas' {FrAddPayment},
  AccountDetailsU in 'AccountDetailsU.pas' {FrAccountDetails},
  AddFinancialNoteU in 'AddFinancialNoteU.pas' {FrAddFinancialNote},
  PrintFinancialNoteU in 'PrintFinancialNoteU.pas' {FrPrintFinancialNote},
  AddLoanU in 'AddLoanU.pas' {FrAddLoan},
  AddLoanTypeU in 'AddLoanTypeU.pas' {FrAddLoanType},
  PrintPartU in 'PrintPartU.pas' {PrintParts},
  LoanPriorityU in 'LoanPriorityU.pas' {FrLoanPriority},
  AddLoanAmountU in 'addloanAmountU.pas' {FrAddLoanAmount},
  AddattachmentU in 'AddattachmentU.pas' {FrAddAttachment},
  PrinterSettingU in 'PrinterSettingU.pas' {frPrinterSetting},
  ImageInsertTextU in 'ImageInsertTextU.pas' {FrImageInsertText},
  MakeMonthlyU in 'MakeMonthlyU.pas' {FrMakeMonthly},
  AddMonthlyTypeU in 'AddMonthlyTypeU.pas' {FrAddMonthlyType},
  AddFamilyU in 'AddFamilyU.pas' {FrAddFamily},
  EditPrAccountNoU in 'EditPrAccountNoU.pas' {FrEditPrAccountNo},
  SystemSettingU in 'SystemSettingU.pas' {FrSystemSetting},
  AddAccountU in 'AddAccountU.pas' {FrAddAccount},
  ReportAccountPaymentsU in 'ReportAccountPaymentsU.pas' {FrReportAccountPayments},
  ReportAccountU in 'ReportAccountU.pas' {FrReportAccount},
  AccountFilterU in 'AccountFilterU.pas' {FrAccountFilter},
  AddAccountAlarmU in 'AddAccountAlarmU.pas' {FrAddAccountAlarm},
  DatabaseMaintenanceU in 'DatabaseMaintenanceU.pas' {FrDatabaseMaintenance},
  MakeTemplateU in 'MakeTemplateU.pas' {FrMakeTemplate},
  AddTextForTemplatesU in 'AddTextForTemplatesU.pas' {FrAddTextForTemplate},
  QrPaymentU in 'QrPaymentU.pas' {FrQrPayment},
  AddSessionU in 'AddSessionU.pas' {FSession},
  PrintSessionU in 'PrintSessionU.pas' {FrPrintSession},
  FinancialNoteDetailU in 'FinancialNoteDetailU.pas' {FrFinancialNoteDetail},
  AddLoanRequestU in 'AddLoanRequestU.pas' {FrAddLoanRequest},
  LoanRequestDialogU in 'LoanRequestDialogU.pas' {FrLoanRequestDialog},
  searchLoanU in 'searchLoanU.pas' {FrSearchLoan},
  ErrorMsgU in 'ErrorMsgU.pas' {FrErrorMsg},
  PayPartU in 'PayPartU.pas' {FrPayPart},
  PayMonthlyU in 'PayMonthlyU.pas' {FrPayMonthly},
  PrintMonthlyU in 'PrintMonthlyU.pas' {FrPrintMonthly},
  AmerceU in 'AmerceU.pas' {FrAmerce},
  LoanPointU in 'LoanPointU.pas' {FrLoanPoint},
  EditPartu in 'EditPartu.pas' {FrEditPart},
  SumPaymentU in 'SumPaymentU.pas' {FrSumPayment},
  Report_GroupForcePaymentU in 'Report_GroupForcePaymentU.pas' {FrReport_GroupForcePayment},
  EditMonthlyU in 'EditMonthlyU.pas' {FrEditMonthly},
  LoanGaurantorU in 'LoanGaurantorU.pas' {FrLoanGaurantor},
  Report_loanPointU in 'Report_loanPointU.pas' {FrReport_loanPoint},
  EditLoanU in 'EditLoanU.pas' {FrEditLoan},
  AddCashPaymentU in 'AddCashPaymentU.pas' {FrAddCashPayment},
  SummeryPaymentU in 'SummeryPaymentU.pas' {FrSummeryPayment},
  BankU in 'BankU.pas' {FrBank},
  Report_ActiveUsers in 'Report_ActiveUsers.pas' {FrReport_ActiveUsers},
  Report_PaymentU in 'Report_PaymentU.pas' {FrReport_Payment},
  EditPaymentU in 'EditPaymentU.pas' {FrEditPayment},
  Daily_ReportU in 'Daily_ReportU.pas' {FrDaily_Report},
  Income_SummeryU in 'Income_SummeryU.pas' {FrIncome_Summery},
  UserLoginLogoutReportU in 'UserLoginLogoutReportU.pas' {FrUserLoginLogoutReport},
  PrintPayment_ByDocumentNoU in 'PrintPayment_ByDocumentNoU.pas' {FQrPrintPayment_ByDocumentNo},
  RestoreU in 'RestoreU.pas' {FrRestore},
  AddForcePaymentU in 'AddForcePaymentU.pas' {frAddForcePayment},
  TransferU in 'TransferU.pas' {FrTransfer},
  AddAccountTypeU in 'AddAccountTypeU.pas' {FrAddAccountType},
  EditAccountTypeU in 'EditAccountTypeU.pas' {FrEditAccountType},
  SummeryPayment_allU in 'SummeryPayment_allU.pas' {FrSummeryPayment_all},
  DividBenefitU in 'DividBenefitU.pas' {FrDividBenefit},
  RepLoanGrtFm in 'RepLoanGrtFm.pas' {FmRepLoanGrt},
  RepLoanGrtDM in 'RepLoanGrtDM.pas' {DMRepLoanGrt: TDataModule},
  SearchFM in 'SearchFM.pas' {FmSearch},
  SumPaymentDM in 'SumPaymentDM.pas' {DMSumPayment: TDataModule},
  ReportAccountPaymentsPBKU in 'ReportAccountPaymentsPBKU.pas' {FrReportAccountPaymentsPBK},
  YInputQuery_Double in 'YInputQuery_Double.pas' {YInputQuery_DoublF},
  AddFinancialNote_NewU in 'AddFinancialNote_NewU.pas' {FrAddFinancialNote_New},
  MainU in 'MainU.pas' {FrMain},
  FinancialNoteDetail_NewU in 'FinancialNoteDetail_NewU.pas' {FrFinancialNoteDetail_New},
  Report_PaymentInDetailU in 'Report_PaymentInDetailU.pas' {FrReport_PaymentInDetail},
  PaymentImportFromExcelU in 'PaymentImportFromExcelU.pas' {FrPaymentImportFromExcel},
  Unit1 in 'Unit1.pas' {Form1},
  Report_LoanPerAccountU in 'Report_LoanPerAccountU.pas' {frReport_LoanPerAccount},
  PerfrajListU in 'PerfrajListU.pas' {FrPerfrajList},
  AvrageU in 'AvrageU.pas' {FrAvrage},
  SumPayment_ReportU in 'SumPayment_ReportU.pas' {FrSumPayment_Report},
  LoanReportU in 'LoanReportU.pas' {FrLoanReport},
  AddRemainLoanU in 'AddRemainLoanU.pas' {FrAddRemainLoan},
  AccDailyReportU in 'AccDailyReportU.pas' {FrAccDailyReport},
  DividBenefit_NewU in 'DividBenefit_NewU.pas' {FrDividBenefit_New},
  RepTotalPayment in 'RepTotalPayment.pas' {YBaseForm1},
  RepTotalPaymentU in 'RepTotalPaymentU.pas' {FrRepTotalPayment},
  AddReportNameU in 'AddReportNameU.pas' {FrAddReportName},
  ListofObjectsU in 'ListofObjectsU.pas' {FrListofObjects},
  ForTest in 'ForTest.pas' {FrForTest},
  AddPresentationDetU in 'AddPresentationDetU.pas' {FrAddPresentationDet},
  ListofContactsU in 'ListofContactsU.pas' {FrListofContacts},
  PrintDeletedPayment_ByDocumentNoU in 'PrintDeletedPayment_ByDocumentNoU.pas' {FrPrintDeletedPayment_ByDocumentNo},
  DocPrintU in 'DocPrintU.pas' {FrDocPrint},
  URepSoodSepordeh in 'URepSoodSepordeh.pas' {FrmRepSoodSepordeh},
  URepSood2 in 'URepSood2.pas' {FmRepSood2},
  UBenefitFromHazineh in 'UBenefitFromHazineh.pas' {fmBenefitFromHazineh},
  SmsCenter1 in 'SmsCenter1.pas',
  uSendSMS in 'uSendSMS.pas' {frmSendSMS},
  uSmsSetting in 'uSmsSetting.pas' {frmSmsSetting},
  v2 in 'SMSunit\v2.pas',
  UnitSMS in 'SMSunit\UnitSMS.pas',
  U_ENTER_IP_ADDRESS_FRM in 'U_ENTER_IP_ADDRESS_FRM.pas' {ENTER_IP_ADDRESS_FRM},
  U_LOCK_ERROR_FRM in 'U_LOCK_ERROR_FRM.pas' {LOCK_ERROR_FRM},
  U_FITCHER_SETTING_FRM in 'U_FITCHER_SETTING_FRM.pas' {FITCHER_SETTING_FRM},
  U_ADV_SEARCH_SANAD_FRM in 'U_ADV_SEARCH_SANAD_FRM.pas' {ADV_SEARCH_SANAD_FRM},
  U_REPORT_BE_TAFKIK_ADV_FRM in 'U_REPORT_BE_TAFKIK_ADV_FRM.pas' {REPORT_BE_TAFKIK_ADV_FRM},
  U_QUICKREP_ADV_SEARCH_VAM_AZA_FRM in 'U_QUICKREP_ADV_SEARCH_VAM_AZA_FRM.pas' {QUICKREP_ADV_SEARCH_VAM_AZA_FRM},
  U_ENTER_ADMIN_PASS_FRM in 'U_ENTER_ADMIN_PASS_FRM.pas' {ENTER_ADMIN_PASS_FRM},
  uUpdateDbScripts in 'uUpdateDbScripts.pas' {fmUpdateDbScripts},
  USearchTitle in 'USearchTitle.pas' {SearchAdoDataSet},
  YShamsiDate in 'YShamsiDate.pas',
  untScript in 'untScript.pas' {frmScript},
  YDbgrid in 'YDbgrid.pas',
  Upreview in 'Upreview.pas' {Fpreview},
  YAmountEdit in 'YAmountEdit.pas',
  YWhereEdit in 'YWhereEdit.pas';


{$R *.res}

{Var
   CoName:String;
   WithDongle:Boolean;}
begin
  Application.Initialize;
  Application.HelpFile := '';
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TFrMain, FrMain);
  Application.Run;
end.
