program Yeganeh_Archive;

uses
  Forms,
  windows,
  BaseUnit in 'BaseUnit.pas' {MBaseForm},
  colorSetting in 'colorSetting.pas' {ColorSettingF},
  FromOrgU in '..\..\..\y dabir\version 4.1\Program\FromOrgU.pas' {FromOrgForm},
  FromOrgDialog in '..\..\..\y dabir\version 4.1\Program\FromOrgDialog.pas' {FromOrgDialogF},
  ExactCopy in '..\..\..\y dabir\version 4.1\Program\ExactCopy.pas' {ExactCopyF},
  Settingsu in 'Settingsu.pas' {Settings},
  ExportToWord in '..\..\..\y dabir\version 4.1\Program\ExportToWord.pas' {FExportToWord},
  USearchTitle in '..\..\..\y dabir\version 4.1\Program\USearchTitle.pas' {SearchAdoDataSet},
  USecChange in 'USecChange.pas' {SecChange},
  UsearchStno in '..\..\..\y dabir\version 4.1\Program\UsearchStno.pas' {SearchStno},
  HelpU in '..\..\..\y dabir\version 4.1\Program\HelpU.pas' {FHelp},
  Uconnect in 'Uconnect.pas' {Fconnect},
  FUserShortCut in '..\..\..\y dabir\version 4.1\Program\FUserShortCut.pas' {UserShortCutF},
  ShowmessageU in '..\..\..\y dabir\version 4.1\Program\ShowmessageU.pas' {ShowMessageF},
  UchangePassword in '..\..\..\y dabir\version 4.1\Program\UchangePassword.pas' {FchangePassword},
  LetterArchive in '..\..\..\y dabir\version 4.1\Program\LetterArchive.pas' {LetterArchiveform},
  CodePage in '..\..\..\y dabir\version 4.1\Program\CodePage.pas',
  PasswordChange in '..\..\..\y dabir\version 4.1\Program\PasswordChange.pas',
  UTotalRecommite in '..\..\..\y dabir\version 4.1\Program\UTotalRecommite.pas' {RecommiteGroup},
  UTotalExactCopy in '..\..\..\y dabir\version 4.1\Program\UTotalExactCopy.pas' {FExactGroup},
  UchangeCricitalFields in '..\..\..\Y Archive\version 4.1\Program\UchangeCricitalFields.pas' {FchangeCricitalFields},
  YShamsiDate in '..\..\..\Vcl\YShamsiDate.pas',
  YInputQuery in '..\..\..\yeganeh shared\YInputQuery.pas' {YInputQueryF},
  about in 'ABOUT.PAS' {AboutBox},
  YeganehDemo in '..\..\..\yeganeh shared\YeganehDemo.pas' {Yeganeh},
  UAddShortCut in 'UAddShortCut.pas' {FrAddShortCut},
  UsearchShortCut in 'UsearchShortCut.pas' {FrsearchShortCut},
  businessLayer in 'businessLayer.pas',
  ArchiveOrganize in 'ArchiveOrganize.pas' {ArchiveOrganizeForm},
  ArchiveDialog in 'ArchiveDialog.pas' {ArchiveDialogForm},
  URetroExist in 'URetroExist.pas' {RetroExist},
  InsertText in 'InsertText.pas' {InsertTextForm},
  ReCommiteU in 'ReCommiteU.pas' {Recommite},
  LetterFilterU in '..\..\..\Y Archive\version 4.1\Program\LetterFilterU.pas' {LetterFilter},
  UMain in '..\..\..\Y Archive\version 4.1\Program\UMain.pas' {MainForm},
  Udailyrep in '..\..\..\Y Archive\version 4.1\Program\Udailyrep.pas' {Fdailyrep},
  UFillLetterData in '..\..\..\Y Archive\version 4.1\Program\UFillLetterData.pas' {FillLetterData},
  UImportFax in '..\Program\UImportFax.pas' {FImportFax},
  userDefine in '..\Program\userDefine.pas' {UserDefineF},
  LogOn in '..\..\..\Y Archive\version 4.1\Program\LogOn.pas' {LoginForm},
  ExitedLetterInputF in '..\..\..\Y Archive\version 4.1\Program\ExitedLetterInputF.pas' {SentLetterInputForm},
  EnteredLetterInputF in '..\..\..\Y Archive\version 4.1\Program\EnteredLetterInputF.pas' {ReceivedLetterInputForm},
  FixedTableF in '..\..\..\Y Archive\version 4.1\Program\FixedTableF.pas' {FixedForm},
  QuickSearch in '..\..\..\Y Archive\version 4.1\Program\QuickSearch.pas' {QuickSearchF},
  ReCommitedialog in '..\..\..\Y Archive\version 4.1\Program\ReCommitedialog.pas' {RecommiteSave},
  AccessInput in '..\Program\AccessInput.pas' {AccessForm},
  backupF in '..\Program\backupF.pas' {BackupRestore},
  Dmu in '..\..\..\Y Archive\version 4.1\Program\Dmu.pas' {dm: TDataModule},
  DuplicateNo in '..\..\..\Y Archive\version 4.1\Program\DuplicateNo.pas' {FDuplicate},
  UInputTemplate in '..\Program\UInputTemplate.pas' {EditTemplates},
  LetterReportU in '..\..\..\Y Archive\version 4.1\Program\LetterReportU.pas' {LetterReport},
  CreateTextU in '..\Program\CreateTextU.pas' {CreateText},
  EditSentense in '..\Program\EditSentense.pas' {FEditSentense},
  FullTextSearch in '..\..\..\Y Archive\version 4.1\Program\FullTextSearch.pas' {FullTextSearchF},
  Fsecretariats in '..\..\..\Y Archive\version 4.1\Program\Fsecretariats.pas' {FEditSecs},
  addUserSecs in '..\..\..\Y Archive\version 4.1\Program\addUserSecs.pas' {FaddUserSecs},
  SystemSetting in '..\..\..\Y Archive\version 4.1\Program\SystemSetting.pas' {SystemSettings},
  ustatistic in '..\..\..\Y Archive\version 4.1\Program\ustatistic.pas' {StatisticForm},
  UserLoginLogoutReportU in '..\Program\UserLoginLogoutReportU.pas' {FUserLoginLogoutReport},
  YArchiveLetterData in '..\Program\YArchiveLetterData.pas' {FArchiveLetterData},
  RestorLetterData in '..\Program\RestorLetterData.pas' {FRestorLetterData},
  UTemplateGroup in '..\Program\UTemplateGroup.pas' {FrUTemplateGroup},
  UEditLetterGroup in '..\Program\UEditLetterGroup.pas' {FEditLetterGroup},
  UaddUserTemplateGroup in '..\Program\UaddUserTemplateGroup.pas' {FaddUserTemplateGroup},
  uAddExtention in '..\Program\uAddExtention.pas' {FrAddExtention},
  UEditUserExtention in '..\Program\UEditUserExtention.pas' {FrEditUserExtention},
  UaddLetterData in '..\Program\UaddLetterData.pas' {FraddLetterData},
  uAddExtentionDialog in '..\Program\uAddExtentionDialog.pas' {FrAddExtentionDialog},
  UAddLetterDataDialog in '..\Program\UAddLetterDataDialog.pas' {FrAddLetterDataDialog},
  UPrinterSetting in 'UPrinterSetting.pas' {frPrinterSetting},
  FActiveUsers in '..\..\..\Y Archive\version 4.1\Program\FActiveUsers.pas' {ActiveUsers},
  ErrorMsg in 'ErrorMsg.pas' {FErrorMsg};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := '** Yeganeh Software Company **';
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
