program yeganehBox;
uses
  Forms,
  BaseUnit in '..\shared\BaseUnit.pas' {MBaseForm},
  UMain in 'UMain.pas' {MainForm},
  Inbox in 'Inbox.pas' {FInbox},
  LogOn in 'LogOn.pas' {LoginForm},
  FromOrgU in '..\shared\FromOrgU.pas' {FromOrgForm},
  FromOrgDialog in '..\shared\FromOrgDialog.pas' {FromOrgDialogF},
  ExitedLetterInputF in 'ExitedLetterInputF.pas' {SentLetterInputForm},
  EnteredLetterInputF in 'EnteredLetterInputF.pas' {ReceivedLetterInputForm},
  ExactCopy in '..\shared\ExactCopy.pas' {ExactCopyF},
  Dmu in 'Dmu.pas' {Dm: TDataModule},
  ExportToWord in '..\shared\ExportToWord.pas' {FExportToWord},
  Utabloo in 'Utabloo.pas' {FBoard},
  USearchTitle in '..\shared\USearchTitle.pas' {SearchAdoDataSet},
  HelpU in '..\shared\HelpU.pas' {FHelp},
  USecChange in '..\shared\USecChange.pas' {SecChange},
  Settingsu in '..\shared\Settingsu.pas' {Settings},
  DoCommite in 'DoCommite.pas' {FDoCommite},
  Uconnect in '..\shared\Uconnect.pas' {Fconnect},
  YeganehDemo in '..\shared\YeganehDemo.pas' {Yeganeh},
  FUserShortCut in '..\shared\FUserShortCut.pas' {UserShortCutF},
  ShowmessageU in '..\shared\ShowmessageU.pas' {ShowMessageF},
  UchangePassword in '..\shared\UchangePassword.pas' {FchangePassword},
  LetterArchive in '..\shared\LetterArchive.pas' {LetterArchiveform},
  ArchiveOrganize in 'ArchiveOrganize.pas' {ArchiveOrganizeForm},
  YInputQuery in '..\shared\YInputQuery.pas' {YInputQueryF},
  UUsernote in 'UUsernote.pas' {FUserNote},
  businessLayer in '..\shared\businessLayer.pas',
  ArchiveDialog in '..\shared\ArchiveDialog.pas' {ArchiveDialogForm},
  UAddShortCut in '..\shared\UAddShortCut.pas' {FrAddShortCut},
  UsearchStno in '..\shared\UsearchStno.pas' {SearchStno},
  UsearchShortCut in '..\shared\UsearchShortCut.pas' {FrsearchShortCut},
  InsertText in '..\shared\InsertText.pas' {InsertTextForm},
  ReCommiteU in '..\shared\ReCommiteU.pas' {Recommite},
  ReCommitedialog in 'ReCommitedialog.pas' {RecommiteSave},
  UPrinterSetting in '..\shared\UPrinterSetting.pas' {frPrinterSetting},
  about in '..\shared\ABOUT.PAS' {AboutBox},
  FActiveUsers in '..\shared\FActiveUsers.pas' {ActiveUsers},
  UloadPDF in '..\shared\UloadPDF.pas' {FLoadPDF},
  UinnerLetter in '..\shared\UinnerLetter.pas' {FinnerLetter},
  UUserTable_Input in '..\shared\UUserTable_Input.pas' {FrUserTable_Input},
  UGetMessage in '..\shared\UGetMessage.pas' {FrGetMessage},
  USendMessage in '..\shared\USendMessage.pas' {FrSendMessage},
  UEditSubject in '..\shared\UEditSubject.pas' {FrEditSubject},
  UAddDocument in '..\shared\UAddDocument.pas' {FrAddDocument},
  UBrowsArchive in '..\shared\UBrowsArchive.pas' {FrBrowsArchive},
  URecommiteTemplate in '..\shared\URecommiteTemplate.pas' {FrRecommiteTemplate},
  UaddLetterData in '..\shared\UaddLetterData.pas' {FraddLetterData},
  UFollowUp in '..\shared\UFollowUp.pas' {FrFollowUp},
  URecommiteReport in '..\shared\URecommiteReport.pas' {FrRecommiteReport},
  URecommitestat in '..\shared\URecommitestat.pas' {FrRecommiteStat},
  insertParaphTemplateU in 'insertParaphTemplateU.pas' {FrInsertParaphTemplate},
  ParaphDialogU in 'ParaphDialogU.pas' {FrParaphDialog},
  AddAlternativeUserU in 'AddAlternativeUserU.pas' {FrAddAlternativeUser},
  ChangeOrgIDU in 'ChangeOrgIDU.pas' {FrChangeOrgID},
  InputPassU in 'InputPassU.pas' {FInputPass},
  SearchFM in '..\shared\SearchFM.pas' {FmSearch},
  RecommiteReportDM in '..\shared\RecommiteReportDM.pas' {DMRecommiteReport: TDataModule},
  ShowMessageFm in 'ShowMessageFm.pas' {FmShowMessage},
  NewsUsersFm in '..\shared\NewsUsersFm.pas' {FmNewsUsers},
  NewsUsersDM in '..\shared\NewsUsersDM.pas' {DMNewsUsers: TDataModule},
  URetroExist in '..\shared\URetroExist.pas' {RetroExist},
  ScanImageFm in '..\shared\ScanImageFm.pas' {FmScanImage},
  ScanImageDM in '..\shared\ScanImageDM.pas' {DMScanImage: TDataModule},
  EmailUserPassFm in '..\shared\EmailUserPassFm.pas' {FmEmailUserPass},
  EmailsDM in '..\shared\EmailsDM.pas' {DMEmails: TDataModule},
  WaitPleaseFM in '..\shared\WaitPleaseFM.pas' {FMWaitPlease},
  EmailsFm in '..\shared\EmailsFm.pas' {FmEmails},
  WorkGroupFM in '..\shared\WorkGroupFM.pas' {FMWorkGroup},
  WorkGroupDM in '..\shared\WorkGroupDM.pas' {DMWorkGroup: TDataModule},
  AllScanImageFm in '..\shared\AllScanImageFm.pas' {FmAllScanImage},
  PhoneFm in '..\shared\PhoneFm.pas' {FmPhone},
  PhoneGroupDM in '..\shared\PhoneGroupDM.pas' {DMPhoneGroup: TDataModule},
  PhoneGroupFm in '..\shared\PhoneGroupFm.pas' {FmPhoneGroup},
  PhoneDM in '..\shared\PhoneDM.pas' {DMPhone: TDataModule},
  PicProgressFm in '..\shared\PicProgressFm.pas' {FmPicProgress},
  PrintFm in '..\shared\PrintFm.pas' {FmPrint},
  AssignLetterIndicatorFm in '..\shared\AssignLetterIndicatorFm.pas' {fmAssignLetterIndicator},
  uRecommiteList in '..\Shared\uRecommiteList.pas' {FrRecommiteList},
  RepMohlateEghdamUnit in 'RepMohlateEghdamUnit.pas' {FRepMohlateEghdam},
  UDP in 'UDP.pas' {UDPSearchForm},
  ContractsUnit in 'ContractsUnit.pas' {frmContracts},
  FlowUpUnit in 'FlowUpUnit.pas' {frmFlowUp},
  CRMDataBaseUnit in 'CRMDataBaseUnit.pas' {CRMDataBaseForm},
  CustomerInfoUnit in 'CustomerInfoUnit.pas' {frmCustomerInfo},
  SearchFromCRMUnit in 'SearchFromCRMUnit.pas' {SearchFromCRM},
  UMyMessage in 'UMyMessage.pas' {FMyMessage},
  WorkSheetViewsUnit in 'WorkSheetViewsUnit.pas' {FWorkSheetViews},
  WorkSheetAllRepUnit in 'WorkSheetAllRepUnit.pas' {FWorkSheetAllRep},
  WorkSheetBaseResultsUnit in 'WorkSheetBaseResultsUnit.pas' {FWorkSheetBaseResults},
  WorkSheetBaseSessionsUnit in 'WorkSheetBaseSessionsUnit.pas' {FWorkSheetBaseSessions},
  WorkSheetBaseTasksUnit in 'WorkSheetBaseTasksUnit.pas' {FWorkSheetBaseTasks},
  WorkSheetBaseUnit in 'WorkSheetBaseUnit.pas' {FWorkSheetBase},
  WorkSheetBaseVisitsUnit in 'WorkSheetBaseVisitsUnit.pas' {FWorkSheetBaseVisits},
  WorkSheetNewsUnit in 'WorkSheetNewsUnit.pas' {FWorkSheetNews},
  WorkSheetSessionResponseUnit in 'WorkSheetSessionResponseUnit.pas' {FWorkSheetSessionResponse},
  WorkSheetVisitResponseUnit in 'WorkSheetVisitResponseUnit.pas' {FWorkSheetVisitResponse},
  WorkSheetTaskResponseUnit in 'WorkSheetTaskResponseUnit.pas' {FWorkSheetTaskResponse},
  UInputUserTable in 'UInputUserTable.pas' {FrInputUserTable},
  ShowSaderehUnit in 'ShowSaderehUnit.pas' {FShowSadereh},
  UGroupUser in '..\Shared\UGroupUser.pas' {FGroupUser},
  FullTextSearch in '..\Program\FullTextSearch.pas' {FullTextSearchF},
  DocumentsListUnit in '..\Shared\DocumentsListUnit.pas' {DocumentsListForm},
  LetterSigners in 'LetterSigners.pas' {fmLetterSigners},
  ImageDataFM in '..\Shared\ImageDataFM.pas' {fmImageData},
  TextSearch in '..\Shared\TextSearch.pas' {TextSearchF},
  ShowArchiveDoc in '..\Program\ShowArchiveDoc.pas',
  FrmFarsi in '..\Program\FrmFarsi.pas' {fmFarsi},
  ArchiveAttach in '..\Program\ArchiveAttach.pas' {fmArchiveAttachment},
  YInputBox in 'YInputBox.pas' {FmInputBox},
  InputUserPassU in '..\Program\InputUserPassU.pas' {FInputUserPass},
  USelArchiveSecID in '..\Program\USelArchiveSecID.pas' {SelArchiveSecID},
  URenameColumn in '..\Program\URenameColumn.pas' {FmRenameColumn},
  YShamsiDate in '..\shared\YShamsiDate.pas',
  untFollowRetroactionLetter in 'untFollowRetroactionLetter.pas' {frmFollowRetroactionLetter},
 
  YDbgrid in '..\..\..\99 - Shared\YDbgrid.pas',
  U_ENTER_IP_ADDRESS_FRM in 'U_ENTER_IP_ADDRESS_FRM.pas' {ENTER_IP_ADDRESS_FRM},
  U_LOCK_ERROR_FRM in 'U_LOCK_ERROR_FRM.pas' {LOCK_ERROR_FRM},
  U_SHOW_ATF_PEYRO_FRM in 'U_SHOW_ATF_PEYRO_FRM.pas' {SHOW_ATF_PEYRO_FRM},
  LetterRalationFm in 'OtherUnit\LetterRalationFm.pas' {FmLetterRalation},
  U_VERSION_INFO_FRM in 'OtherUnit\U_VERSION_INFO_FRM.pas' {VERSION_INFO_FRM},
  U_VERSION_INFO_EDIT_FRM in 'OtherUnit\U_VERSION_INFO_EDIT_FRM.pas' {VERSION_INFO_EDIT_FRM},
  U_SEE_PAYVAST_ERJA_FRM in 'U_SEE_PAYVAST_ERJA_FRM.pas' {SEE_PAYVAST_ERJA_FRM},
  U_ADD_PEYVAST_DIALOG_FRM in 'OtherUnit\U_ADD_PEYVAST_DIALOG_FRM.pas' {ADD_PEYVAST_DIALOG_FRM},
  UAddLetterDataDialog in 'OtherUnit\UAddLetterDataDialog.pas' {FrAddLetterDataDialog},
  frmMain in 'frmMain.pas' {Form_WorkGroupFM};

{$R *.res}
{$R dbnavigatorIcon.RES}
//{$R DBNavBitmap.res}

begin
  Application.Initialize;
  Application.Title := '‘—ﬂ  ‰—„ «›“«—Ì Ìê«‰Â';
  {$IFDEF ADA}
      Application.Title := '‘—ﬂ  ‰—„ «›“«—Ì ¬œ«';
  {$ENDIF}
  Application.CreateForm(TDm, Dm);
  Application.CreateForm(TMainForm, MainForm);
  Application.CreateForm(TFInbox, FInbox);
  Application.CreateForm(TFmLetterRalation, FmLetterRalation);
  Application.CreateForm(TFrAddLetterDataDialog, FrAddLetterDataDialog);
  Application.CreateForm(TForm_WorkGroupFM, Form_WorkGroupFM);
  Application.Run;
end.
